import type { Metadata } from "next";
import { Crimson_Pro } from "next/font/google";
import "./styles/globals.scss";
import { MainNavigation } from "@/app/components/mainNavigation/MainNavigation";

const crimsonPro = Crimson_Pro({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-crimson-pro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${crimsonPro.variable}`}>
        <MainNavigation></MainNavigation>
        {children}
      </body>
    </html>
  );
}
